FROM golang:1.25-alpine AS builder
WORKDIR /app

# Download dependencies
COPY go.mod go.sum ./
RUN go mod download

# Build importer
COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build -ldflags="-s -w" -o /import-csv ./cmd/import-csv-embedded

# ── Runtime Stage ────────────────────────────────────────────────────────────
FROM alpine:3.20

RUN apk --no-cache add ca-certificates

WORKDIR /app

# Copy binary
COPY --from=builder /import-csv .

# Run importer when container starts
CMD ["./import-csv"]
